# Generated by Django 3.0.3 on 2020-10-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('alertCO', models.IntegerField()),
                ('alertSmoke', models.IntegerField()),
                ('alertLpg', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smoky.User')),
            ],
        ),
    ]
